
# Server configuration
quarkus.virtual-threads.name-prefix=VirtualThreadQCD
quarkus.virtual-threads.enabled=true
quarkus.http.port=8080
quarkus.package.jar.type=uber-jar

# Hibernate configuration
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.datasource.*.jdbc.max-size=20
quarkus.datasource.*.jdbc.min-size=1

# api documentation
quarkus.swagger-ui.enable=true
quarkus.swagger-ui.always-include=true
quarkus.swagger-ui.path=/swagger
quarkus.smallrye-openapi.path=/docs
quarkus.smallrye-openapi.enable=true
quarkus.smallrye-openapi.info-title=Enterprise API Middleware
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=APIs for core enterprise integration services.
quarkus.smallrye-openapi.info-contact-email=devteam@example.com
quarkus.smallrye-openapi.info-license-name=Apache 2.0
quarkus.smallrye-openapi.info-license-url=http://www.apache.org/licenses/LICENSE-2.0.html


# application.properties
quarkus.native.builder-image=quay.io/quarkus/ubi9-quarkus-mandrel-builder-image:jdk-25